// audit.js — usage: node audit.js <url> <slug> [--sections=N] [--desktopOnly] [--mobileOnly] [--noScroll] [--noHover]
const { chromium } = require('playwright-core');
const fs = require('fs');
const path = require('path');

const EDGE = 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const OUT_ROOT = path.resolve(__dirname, '..', 'evidence');
const [, , url, slug, ...rest] = process.argv;
if (!url || !slug) { console.error('usage: node audit.js <url> <slug>'); process.exit(1); }
const opts = Object.fromEntries(rest.map(a => { const m = a.match(/^--(\w+)(?:=(.*))?$/); return m ? [m[1], m[2] ?? true] : [a, true]; }));
const MAX_SECTIONS = parseInt(opts.sections || '28', 10);

const VIEWPORTS = {
  desktop: { viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, isMobile: false, hasTouch: false,
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36' },
  mobile: { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true,
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1' },
};

const URL_PATTERNS = [
  ['Next.js', /\/_next\//], ['Nuxt', /\/_nuxt\//], ['Gatsby', /\/page-data\//], ['Webflow', /webflow\.com|\.webflow\./i], ['Framer site builder', /framerusercontent|framerstatic/i],
  ['Lovable', /lovable/i], ['WordPress', /wp-content|wp-includes|wp-json/i], ['Elementor', /elementor/i], ['Vite build', /\/assets\/index-[\w-]+\.js/], ['Astro', /\/_astro\//],
  ['GSAP (file)', /gsap/i], ['Lenis (file)', /lenis/i], ['Swiper (file)', /swiper/i], ['AOS (file)', /\/aos\./i], ['Lottie (file)', /lottie/i], ['three.js (file)', /three(\.min)?\.js/i], ['Spline', /splinetool|spline\.design/i],
  ['Bootstrap (file)', /bootstrap/i], ['jQuery (file)', /jquery/i], ['Tailwind CDN', /cdn\.tailwindcss/i], ['Google Fonts', /fonts\.googleapis|fonts\.gstatic/i], ['Adobe Fonts', /use\.typekit/i],
  ['Google Tag Manager', /googletagmanager/i], ['Google Analytics', /google-analytics|\/gtag\//i], ['Hotjar', /hotjar/i], ['Calendly', /calendly/i], ['HubSpot', /hubspot|hs-scripts|hsforms/i], ['Vercel', /vercel-insights|_vercel\//i],
  ['Meta Pixel', /connect\.facebook\.net/i], ['MS Clarity', /clarity\.ms/i], ['Sentry', /sentry/i], ['Intercom', /intercom/i], ['Tawk.to', /tawk\.to/i], ['Crisp', /crisp\.chat/i], ['Zoho SalesIQ', /salesiq\.zoho/i], ['LinkedIn Insight', /snap\.licdn/i], ['Cloudflare', /cloudflareinsights|cdn-cgi/i], ['YouTube embed', /youtube\.com\/embed|youtube-nocookie/i], ['Vimeo', /player\.vimeo/i], ['Formspree', /formspree/i], ['reCAPTCHA', /recaptcha/i], ['Cal.com', /cal\.com/i],
];
const BODY_SIGNATURES = [
  ['GSAP', /gsap|_gsap|GSAPTarget|gsapVersion/, 'js'], ['ScrollTrigger', /ScrollTrigger/, 'js'], ['Lenis', /\bLenis\b|lenis/, 'js'], ['framer-motion / motion', /framer-motion|AnimatePresence|MotionConfig|useReducedMotion|data-framer-appear-id|projectionNodeConstructor|motion\.dev/, 'js'],
  ['React', /react-dom|__reactFiber|createElement\(|_jsx\(|react\.production/, 'js'], ['Vue', /__vue__|createApp\(|Vue\.createApp|vue\.runtime/, 'js'], ['Swiper', /swiper/i, 'js'], ['Embla carousel', /embla/i, 'js'], ['keen-slider', /keen-slider/i, 'js'], ['Slick carousel', /slick-slider|slick\.min/i, 'js'],
  ['Lottie', /lottie|dotlottie/i, 'js'], ['three.js', /THREE\.|three\.module|WebGLRenderer/, 'js'], ['Spline runtime', /@splinetool|spline-viewer/i, 'js'], ['AOS', /AOS\.init|data-aos/, 'js'], ['Radix UI', /radix-ui|data-radix-|RadixUI/i, 'js'], ['lucide-react', /lucide/i, 'js'], ['Tabler icons', /tabler-icon/i, 'js'], ['react-icons', /react-icons/i, 'js'], ['Typewriter', /typewriter/i, 'js'], ['Particles.js/tsParticles', /tsparticles|particles\.js/i, 'js'], ['Locomotive Scroll', /locomotive/i, 'js'], ['jQuery', /jQuery\.fn|jquery/i, 'js'], ['Alpine.js', /Alpine\.|alpinejs/i, 'js'], ['Bootstrap JS', /bootstrap|\.tooltip\(|Popper/i, 'js'], ['Splitting/SplitText', /SplitText|splitting/i, 'js'], ['Magic UI style markers', /magicui|BorderBeam|ShimmerButton|AnimatedGradientText|DotPattern|InteractiveGridPattern|VelocityScroll/i, 'js'], ['Aceternity style markers', /aceternity|BackgroundBeams|SparklesCore/i, 'js'], ['shadcn cn() helper', /clsx|tailwind-merge|twMerge/i, 'js'],
  ['Tailwind CSS (--tw- vars)', /--tw-/, 'css'], ['Tailwind v4 (@layer theme / --color-)', /--color-[a-z]+-\d{2,3}:|--spacing:|--default-font-family|--font-sans:/, 'css'], ['Bootstrap 5 (--bs- vars)', /--bs-/, 'css'], ['shadcn/ui tokens (--radius/--primary/--muted)', /--radius:[^;]+;[\s\S]*--muted|--muted-foreground|--card-foreground/, 'css'], ['animate.css', /animate__animated|Animate\.css/i, 'css'], ['AOS (css)', /\[data-aos/, 'css'], ['Swiper (css)', /\.swiper-/, 'css'], ['Boxicons', /boxicons|\.bx-/i, 'css'], ['Font Awesome', /font-awesome|\.fa-|fontawesome/i, 'css'], ['Flaticon', /flaticon/i, 'css'], ['Inter font', /font-family:\s*['"]?Inter/i, 'css'], ['Geist font', /Geist/, 'css'], ['Custom @font-face count', /@font-face/g, 'css'], ['prefers-reduced-motion handling', /prefers-reduced-motion/, 'css'], ['Google Fonts @import', /fonts\.googleapis\.com/, 'css'], ['Lenis (css)', /\.lenis/, 'css'], ['GSAP pin-spacer (css)', /pin-spacer/, 'css'],
];

function extractInPage({ maxSections }) {
  const cs = (el) => getComputedStyle(el);
  const txt = (el) => (el && el.textContent || '').replace(/\s+/g, ' ').trim();
  const q = (s) => Array.from(document.querySelectorAll(s));
  const meta = (n) => { const m = document.querySelector(`meta[name="${n}"], meta[property="${n}"]`); return m ? m.getAttribute('content') : null; };
  const out = {};
  out.title = document.title; out.lang = document.documentElement.lang || null;
  out.meta = { description: meta('description'), robots: meta('robots'), viewport: meta('viewport'), ogTitle: meta('og:title'), ogDescription: meta('og:description'), ogImage: meta('og:image'), twitterCard: meta('twitter:card'), generator: meta('generator'), themeColor: meta('theme-color'), keywords: meta('keywords') };
  out.canonical = (document.querySelector('link[rel="canonical"]') || {}).href || null;
  out.favicon = q('link[rel*="icon"]').map(l => l.href).slice(0, 4);
  out.preloads = q('link[rel="preload"], link[rel="preconnect"], link[rel="dns-prefetch"]').map(l => `${l.rel}:${(l.as || '')}:${l.href.slice(0, 100)}`).slice(0, 20);
  out.headings = q('h1,h2,h3,h4').slice(0, 150).map(h => ({ tag: h.tagName, text: txt(h).slice(0, 140) }));
  out.h1Count = q('h1').length; out.h1 = q('h1').map(h => txt(h).slice(0, 200));
  out.wordCount = txt(document.body).split(' ').length;
  out.jsonLd = q('script[type="application/ld+json"]').map(s => { try { return JSON.parse(s.textContent) } catch { return { parseError: true, raw: s.textContent.slice(0, 300) } } });
  out.fonts = { loaded: [] };
  try { document.fonts.forEach(f => out.fonts.loaded.push({ family: f.family, weight: f.weight, style: f.style, status: f.status })); } catch { }
  const sampleEls = { html: document.documentElement, body: document.body, h1: document.querySelector('h1'), h2: document.querySelector('h2'), h3: document.querySelector('h3'), p: q('p').find(p => txt(p).length > 60) || document.querySelector('p'), navLink: document.querySelector('nav a, header a'), button: document.querySelector('a.btn, a[class*="btn"], a[class*="button"], button, [role="button"]'), header: document.querySelector('header, nav'), footer: document.querySelector('footer') };
  out.typography = {}; for (const [k, el] of Object.entries(sampleEls)) { if (!el) continue; const s = cs(el); out.typography[k] = { fontFamily: s.fontFamily, fontSize: s.fontSize, fontWeight: s.fontWeight, lineHeight: s.lineHeight, letterSpacing: s.letterSpacing, color: s.color, bg: s.backgroundColor, textTransform: s.textTransform }; }
  const famCount = {}, sizeCount = {}, colorCount = {}, bgCount = {}, radiusCount = {}, shadowCount = {}, transitions = {}, gradients = new Set(), borders = {}, blurs = {};
  const all = q('body *').slice(0, 7000);
  let smallText = 0;
  for (const el of all) { const s = cs(el); if (s.display === 'none' || s.visibility === 'hidden') continue; const hasText = Array.from(el.childNodes).some(n => n.nodeType === 3 && n.textContent.trim()); if (hasText) { famCount[s.fontFamily] = (famCount[s.fontFamily] || 0) + 1; sizeCount[s.fontSize] = (sizeCount[s.fontSize] || 0) + 1; colorCount[s.color] = (colorCount[s.color] || 0) + 1; if (parseFloat(s.fontSize) < 12) smallText++; } if (s.backgroundColor && s.backgroundColor !== 'rgba(0, 0, 0, 0)') bgCount[s.backgroundColor] = (bgCount[s.backgroundColor] || 0) + 1; if (s.backgroundImage && s.backgroundImage.includes('gradient')) gradients.add(s.backgroundImage.slice(0, 220)); if (s.borderRadius && s.borderRadius !== '0px') radiusCount[s.borderRadius] = (radiusCount[s.borderRadius] || 0) + 1; if (s.boxShadow && s.boxShadow !== 'none') { const k = s.boxShadow.slice(0, 140); shadowCount[k] = (shadowCount[k] || 0) + 1; } if (s.borderStyle !== 'none' && parseFloat(s.borderWidth) > 0) { const k = `${s.borderWidth} ${s.borderColor}`; borders[k] = (borders[k] || 0) + 1; } if (s.backdropFilter && s.backdropFilter !== 'none') blurs[s.backdropFilter] = (blurs[s.backdropFilter] || 0) + 1; if (s.transitionDuration && s.transitionDuration !== '0s') { const key = `${s.transitionProperty} ${s.transitionDuration} ${s.transitionTimingFunction}`.slice(0, 160); transitions[key] = (transitions[key] || 0) + 1; } }
  const top = (o, n = 12) => Object.entries(o).sort((a, b) => b[1] - a[1]).slice(0, n).map(([k, v]) => ({ value: k, count: v }));
  out.tokens = { fontFamilies: top(famCount), fontSizes: top(sizeCount, 18), textColors: top(colorCount), backgrounds: top(bgCount), radii: top(radiusCount), shadows: top(shadowCount, 8), borders: top(borders, 8), backdropBlur: top(blurs, 5), gradients: Array.from(gradients).slice(0, 14), transitions: top(transitions, 12) };
  const vars = {}; const keyframes = new Set(); let cssRules = 0, cssErr = 0, reducedMotion = false;
  for (const sh of Array.from(document.styleSheets)) { let rules; try { rules = sh.cssRules; } catch { cssErr++; continue; } for (const r of Array.from(rules)) { cssRules++; if (r.type === 1 && /(^|,)\s*(:root|html|body|\.dark|\[data-theme[^\]]*\])\s*($|,)/.test(r.selectorText || '')) { for (const p of Array.from(r.style)) if (p.startsWith('--')) vars[p] = r.style.getPropertyValue(p).trim().slice(0, 120); } else if (r.type === 7) keyframes.add(r.name); else if (r.type === 4) { if (/prefers-reduced-motion/.test(r.conditionText || (r.media && r.media.mediaText) || '')) reducedMotion = true; for (const rr of Array.from(r.cssRules || [])) if (rr.type === 7) keyframes.add(rr.name); } } }
  out.cssVars = Object.fromEntries(Object.entries(vars).slice(0, 200)); out.cssVarCount = Object.keys(vars).length; out.keyframes = Array.from(keyframes).slice(0, 80); out.cssRuleCount = cssRules; out.cssSheetsBlocked = cssErr; out.reducedMotionRule = reducedMotion;
  out.buttons = q('a.btn, button, a[class*="btn"], a[class*="button"], [role="button"], a[class*="cta"]').filter(b => txt(b) && b.getBoundingClientRect().width > 0).slice(0, 12).map(b => { const s = cs(b); const r = b.getBoundingClientRect(); return { text: txt(b).slice(0, 40), tag: b.tagName, href: (b.getAttribute('href') || '').slice(0, 80), bg: s.backgroundColor, bgImage: s.backgroundImage.slice(0, 140), color: s.color, radius: s.borderRadius, padding: s.padding, fontSize: s.fontSize, fontWeight: s.fontWeight, border: s.border.slice(0, 60), shadow: s.boxShadow.slice(0, 100), transition: `${s.transitionProperty} ${s.transitionDuration} ${s.transitionTimingFunction}`.slice(0, 120), w: Math.round(r.width), h: Math.round(r.height) }; });
  const links = q('a[href]'); const origin = location.origin; const internal = new Set(), external = new Set(); let emptyLinks = 0;
  for (const a of links) { const h = a.href; if (!txt(a) && !a.querySelector('img,svg') && !a.getAttribute('aria-label') && !a.getAttribute('title')) emptyLinks++; if (h.startsWith(origin)) internal.add(h.split('#')[0]); else if (/^https?:/.test(h)) external.add(h); }
  out.links = { total: links.length, internal: Array.from(internal).slice(0, 250), external: Array.from(external).slice(0, 80), emptyText: emptyLinks, tel: [...new Set(links.filter(a => a.href.startsWith('tel:')).map(a => a.href))], mailto: [...new Set(links.filter(a => a.href.startsWith('mailto:')).map(a => a.href))], hashOnly: links.filter(a => a.getAttribute('href') === '#').length, ctaTexts: [...new Set(links.filter(a => /btn|button|cta/i.test(a.className)).map(a => txt(a).slice(0, 40)))].slice(0, 20) };
  const imgs = q('img'); out.images = { total: imgs.length, missingAlt: imgs.filter(i => !i.hasAttribute('alt')).length, emptyAlt: imgs.filter(i => i.getAttribute('alt') === '').length, lazy: imgs.filter(i => i.loading === 'lazy').length, nextImage: imgs.filter(i => /\/_next\/image|srcset/.test(i.outerHTML)).length, formats: {}, oversized: [], missingAltSample: imgs.filter(i => !i.hasAttribute('alt')).slice(0, 8).map(i => (i.currentSrc || i.src).slice(0, 120)), noDimensions: imgs.filter(i => !i.getAttribute('width') && !i.getAttribute('height') && !/aspect-ratio|height/.test(i.getAttribute('style') || '')).length };
  for (const i of imgs) { const src = (i.currentSrc || i.src || ''); const ext = (src.match(/\.(avif|webp|png|jpe?g|svg|gif)(\?|$)/i) || [])[1]; const k = ext ? ext.toLowerCase() : (src.startsWith('data:') ? 'data' : (/_next\/image|imgix|cloudinary|\?w=|fm=/.test(src) ? 'optimised-service' : 'other')); out.images.formats[k] = (out.images.formats[k] || 0) + 1; const r = i.getBoundingClientRect(); if (i.naturalWidth && r.width && i.naturalWidth > r.width * 2.2 && r.width > 50) out.images.oversized.push({ src: src.slice(0, 120), natural: `${i.naturalWidth}x${i.naturalHeight}`, rendered: `${Math.round(r.width)}x${Math.round(r.height)}` }); }
  out.images.oversized = out.images.oversized.slice(0, 12);
  out.media = { videos: q('video').map(v => ({ src: (v.currentSrc || v.src || (v.querySelector('source') || {}).src || '').slice(0, 120), autoplay: v.autoplay, muted: v.muted, loop: v.loop })).slice(0, 6), iframes: q('iframe').map(f => f.src.slice(0, 120)).slice(0, 10), canvas: q('canvas').length, svgInline: q('svg').length, lottie: q('lottie-player, dotlottie-player, [class*="lottie"]').length, spline: q('spline-viewer').length };
  const header = document.querySelector('header, nav, [class*="navbar"], [class*="Navbar"], [class*="header"]');
  const hs = header ? cs(header) : null; const hp = header ? (hs.position === 'fixed' || hs.position === 'sticky' ? hs.position : (header.parentElement ? cs(header.parentElement).position : null)) : null;
  out.layout = { scrollWidth: document.documentElement.scrollWidth, innerWidth: innerWidth, horizontalOverflow: document.documentElement.scrollWidth > innerWidth + 1, pageHeight: Math.max(document.body.scrollHeight, document.documentElement.scrollHeight), hasHamburger: !!document.querySelector('[class*="hamburger"], [class*="burger"], [class*="navbar-toggler"], [class*="menu-toggle"], button[aria-label*="menu" i], [class*="mobile-menu"], [class*="MobileMenu"], [class*="menu-btn"]'), headerPosition: hp, headerBg: hs ? hs.backgroundColor : null, headerBlur: hs ? hs.backdropFilter : null, headerHeight: header ? Math.round(header.getBoundingClientRect().height) : null, smallTextCount: smallText, smallTapTargets: q('a[href], button').filter(el => { const r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0 && (r.width < 40 || r.height < 40); }).length, containerMaxWidth: (() => { const c = document.querySelector('.container, [class*="max-w-"], [class*="container"], [class*="wrapper"]'); return c ? cs(c).maxWidth + ' / ' + Math.round(c.getBoundingClientRect().width) + 'px' : null; })(), bodyBg: cs(document.body).backgroundColor, htmlBg: cs(document.documentElement).backgroundColor, darkTheme: (() => { const m = cs(document.body).backgroundColor.match(/\d+/g); if (!m) return null; const [r, g, b] = m.map(Number); return (0.299 * r + 0.587 * g + 0.114 * b) < 100; })(), cursorCustom: !!document.querySelector('[class*="cursor"], #cursor, .custom-cursor'), scrollSmooth: cs(document.documentElement).scrollBehavior, colorScheme: cs(document.documentElement).colorScheme };
  let skips = 0, prev = 0; for (const h of q('h1,h2,h3,h4,h5,h6')) { const l = +h.tagName[1]; if (prev && l > prev + 1) skips++; prev = l; }
  out.a11y = { headingSkips: skips, buttonsNoName: q('button').filter(b => !txt(b) && !b.getAttribute('aria-label') && !b.querySelector('img[alt]') && !b.getAttribute('title')).length, formInputsNoLabel: q('input:not([type=hidden]):not([type=submit]), textarea, select').filter(i => !(i.labels && i.labels.length) && !i.getAttribute('aria-label') && !i.getAttribute('placeholder')).length, formInputs: q('input:not([type=hidden]), textarea, select').length, forms: q('form').length, skipLink: !!document.querySelector('a[href="#main"], a[href="#content"], [class*="skip"]'), landmarks: { main: q('main').length, nav: q('nav').length, header: q('header').length, footer: q('footer').length }, focusOutlineRemoved: (() => { for (const sh of Array.from(document.styleSheets)) { try { for (const r of Array.from(sh.cssRules)) if (r.type === 1 && /:focus/.test(r.selectorText) && /outline:\s*(none|0)/.test(r.style.cssText)) return true; } catch { } } return false; })(), contrastIssues: [] };
  const lum = (rgb) => { const m = rgb.match(/\d+(\.\d+)?/g); if (!m) return null; if (m[3] !== undefined && parseFloat(m[3]) < 0.99) return null; const [r, g, b] = m.slice(0, 3).map(v => { v = v / 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); }); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
  const bgOf = (el) => { let e = el; while (e) { const s = cs(e); if (s.backgroundImage !== 'none') return null; if (s.backgroundColor && s.backgroundColor !== 'rgba(0, 0, 0, 0)') { const m = s.backgroundColor.match(/\d+(\.\d+)?/g); if (m && m[3] !== undefined && parseFloat(m[3]) < 0.99) return null; return s.backgroundColor; } e = e.parentElement; } return 'rgb(255, 255, 255)'; };
  const seen = {}; for (const el of q('p, a, span, li, h1, h2, h3, h4, button, label, small, div').slice(0, 2500)) { const hasText = Array.from(el.childNodes).some(n => n.nodeType === 3 && n.textContent.trim().length > 2); if (!hasText) continue; const s = cs(el); if (s.display === 'none' || s.visibility === 'hidden' || parseFloat(s.opacity) === 0) continue; const bg = bgOf(el); if (!bg) continue; const l1 = lum(s.color), l2 = lum(bg); if (l1 == null || l2 == null) continue; const ratio = (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05); const fz = parseFloat(s.fontSize); const large = fz >= 24 || (fz >= 18.66 && parseInt(s.fontWeight) >= 700); const min = large ? 3 : 4.5; if (ratio < min) { const key = `${s.color}|${bg}|${s.fontSize}`; if (seen[key]) continue; seen[key] = 1; out.a11y.contrastIssues.push({ text: txt(el).slice(0, 50), color: s.color, bg, fontSize: s.fontSize, ratio: +ratio.toFixed(2) }); } }
  out.a11y.contrastIssues = out.a11y.contrastIssues.slice(0, 15);
  out.animationMarkers = { aos: q('[data-aos]').length, animateCss: q('[class*="animate__"], .wow').length, inlineTransforms: q('[style*="transform"]').length, inlineOpacityZero: q('[style*="opacity: 0"], [style*="opacity:0"]').length, gsapPin: q('.pin-spacer').length, marqueeLike: q('[class*="marquee"], [class*="ticker"], [class*="scroller"], [class*="infinite"]').length, swiper: q('.swiper').length, otherSliders: q('[class*="slick"], [class*="carousel"], [class*="embla"], [class*="keen"], [class*="splide"]').length, cssAnimated: all.filter(el => { const s = cs(el); return s.animationName && s.animationName !== 'none'; }).length, willChange: q('[style*="will-change"]').length, motionDataAttrs: q('[data-framer-appear-id], [data-projection-id], [data-motion]').length, lenisRoot: !!document.querySelector('.lenis, [data-lenis]'), splitText: q('[class*="split"], .word, .char').length };
  out.globals = { nextData: !!document.querySelector('script#__NEXT_DATA__'), nextApp: !!window.__next_f, nuxt: !!window.__NUXT__ || !!document.querySelector('#__nuxt'), gsap: !!window.gsap, scrollTrigger: !!window.ScrollTrigger, lenis: !!(window.Lenis || window.lenis), jquery: !!window.jQuery, reactRoot: !!(document.querySelector('#__next, #root, [data-reactroot]')) || Object.keys(document.body).some(k => k.startsWith('__react')), vue: !!window.Vue || !!document.querySelector('[data-v-app]'), wp: !!window.wp || !!document.querySelector('link[href*="wp-content"]'), webflow: !!window.Webflow, framer: !!document.querySelector('[data-framer-name], [data-framer-component-type]'), tailwindClasses: q('[class]').filter(e => /(^|\s)(flex|grid|px-\d|py-\d|text-(sm|lg|xl|\dxl)|bg-\w+-\d{3}|rounded(-\w+)?|gap-\d)(\s|$)/.test(String(e.className))).length, bootstrapGrid: q('.row .col-lg-6, .row .col-md-6, .row [class*="col-"]').length, swiper: !!window.Swiper, aos: !!window.AOS, lottie: !!window.lottie, three: !!window.THREE, generator: meta('generator') };
  const vw = innerWidth; const cand = [];
  const pushEl = (el) => { if (!el || el.nodeType !== 1) return; const r = el.getBoundingClientRect(); if (r.height < 90 || r.width < vw * 0.5) return; const tag = el.tagName.toLowerCase(); if (['script', 'style', 'noscript', 'svg', 'img', 'picture', 'video', 'iframe'].includes(tag)) return; cand.push({ el, top: Math.round(r.top + scrollY), height: Math.round(r.height) }); };
  q('header, nav, section, footer, article, aside, main > *, body > *, #__next > *, #__next > * > *, #root > *, #root > * > *, main > * > *, [class*="section"], [class*="Section"], [class*="hero"], [class*="Hero"], [class*="banner"], [class*="footer"], [class*="Footer"]').forEach(pushEl);
  cand.sort((a, b) => a.top - b.top || b.height - a.height);
  const kept = [];
  for (const c of cand) { if (kept.some(k => k.el === c.el)) continue; const innerAll = cand.filter(o => o.el !== c.el && c.el.contains(o.el) && o.height < c.height * 0.85); const inner = innerAll.filter(o => !innerAll.some(p => p !== o && p.el.contains(o.el))); const innerH = inner.reduce((a, o) => a + o.height, 0); if (inner.length >= 2 && innerH >= c.height * 0.5) continue; if (kept.find(k => k.el.contains(c.el))) continue; if (kept.find(k => Math.abs(k.top - c.top) < 20 && Math.abs(k.height - c.height) < 20)) continue; kept.push(c); }
  kept.sort((a, b) => a.top - b.top);
  out.sections = kept.slice(0, maxSections).map((k, i) => { const el = k.el; const s = cs(el); const h = el.querySelector('h1,h2,h3'); const ctas = Array.from(el.querySelectorAll('a.btn, button, a[class*="btn"], a[class*="button"], a[class*="cta"], [role="button"]')).map(b => txt(b).slice(0, 40)).filter(Boolean); const bgEl = (() => { let e = el; for (let d = 0; d < 3 && e; d++) { const ss = cs(e); if (ss.backgroundColor !== 'rgba(0, 0, 0, 0)' || ss.backgroundImage !== 'none') return ss; e = e.firstElementChild; } return s; })(); return { i, tag: el.tagName.toLowerCase(), id: el.id || null, cls: String(el.className).slice(0, 90), top: k.top, height: k.height, heading: h ? txt(h).slice(0, 120) : null, headingTag: h ? h.tagName : null, eyebrow: (() => { const e = el.querySelector('span, small, p'); const t = e ? txt(e) : ''; return t && t.length < 40 ? t : null; })(), text: txt(el).slice(0, 220), ctas: [...new Set(ctas)].slice(0, 6), imgs: el.querySelectorAll('img').length, svgs: el.querySelectorAll('svg').length, videos: el.querySelectorAll('video, iframe').length, cards: el.querySelectorAll('[class*="card"], [class*="Card"], [class*="item"], [class*="box"]').length, bg: bgEl.backgroundColor, bgImage: bgEl.backgroundImage.slice(0, 120), padding: s.paddingTop + ' / ' + s.paddingBottom, animation: { aos: el.querySelectorAll('[data-aos]').length, inlineTransform: el.querySelectorAll('[style*="transform"]').length, opacity0: el.querySelectorAll('[style*="opacity: 0"], [style*="opacity:0"]').length, cssAnim: Array.from(el.querySelectorAll('*')).slice(0, 400).filter(e => cs(e).animationName !== 'none').length, transitions: Array.from(el.querySelectorAll('a, button, [class*="card"]')).slice(0, 100).filter(e => cs(e).transitionDuration !== '0s').length }, grid: (() => { const g = el.querySelector('[class*="grid"], .row, [class*="cols"]'); if (!g) return null; const gs = cs(g); return gs.display === 'grid' ? `grid: ${gs.gridTemplateColumns.split(' ').length} cols` : (gs.display === 'flex' ? 'flex' : gs.display); })() }; });
  return out;
}

async function hoverProbe(page) {
  const targets = await page.evaluate(() => {
    const sel = 'a.btn, button, a[class*="btn"], a[class*="button"], [role="button"], [class*="card"], [class*="Card"], [class*="service"] a, nav a, [class*="item"] a';
    const seen = new Set(); const out = [];
    for (const el of document.querySelectorAll(sel)) { const r = el.getBoundingClientRect(); if (r.width < 40 || r.height < 20) continue; if (r.top + scrollY > 7000) continue; const key = String(el.className).slice(0, 60) + '|' + el.tagName; if (seen.has(key)) continue; seen.add(key); el.setAttribute('data-hp', String(out.length)); out.push({ idx: out.length, tag: el.tagName, cls: String(el.className).slice(0, 80), text: (el.textContent || '').trim().slice(0, 40), top: Math.round(r.top + scrollY) }); if (out.length >= 10) break; }
    return out;
  });
  const grab = (el) => { const s = getComputedStyle(el); return { transform: s.transform, boxShadow: s.boxShadow.slice(0, 120), bg: s.backgroundColor, color: s.color, borderColor: s.borderColor, filter: s.filter, opacity: s.opacity, bgImage: s.backgroundImage.slice(0, 100), scale: s.scale, translate: s.translate, transition: `${s.transitionProperty} | ${s.transitionDuration} | ${s.transitionTimingFunction}`.slice(0, 200) }; };
  const results = [];
  for (const t of targets) {
    const loc = page.locator(`[data-hp="${t.idx}"]`).first();
    try {
      await loc.scrollIntoViewIfNeeded({ timeout: 3000 }); await page.waitForTimeout(350);
      const before = await loc.evaluate(grab);
      await loc.hover({ timeout: 3000, force: true }); await page.waitForTimeout(650);
      const after = await loc.evaluate(grab);
      const changed = {}; for (const k of Object.keys(before)) if (k !== 'transition' && before[k] !== after[k]) changed[k] = { before: before[k], after: after[k] };
      results.push({ ...t, transition: before.transition, changed });
    } catch (e) { results.push({ ...t, error: e.message.slice(0, 100) }); }
  }
  await page.mouse.move(0, 0).catch(() => { });
  return results;
}

(async () => {
  const outDir = path.join(OUT_ROOT, slug); fs.mkdirSync(path.join(outDir, 'sections'), { recursive: true });
  const browser = await chromium.launch({ executablePath: EDGE, headless: true, args: ['--disable-blink-features=AutomationControlled', '--no-first-run', '--disable-gpu', '--hide-scrollbars'] });
  const result = { url, slug, capturedAt: new Date().toISOString(), tool: 'playwright-core 1.63 + Microsoft Edge 154 headless (Chromium)', viewports: {} };
  for (const [vpName, vp] of Object.entries(VIEWPORTS)) {
    if (opts.mobileOnly && vpName !== 'mobile') continue; if (opts.desktopOnly && vpName !== 'desktop') continue;
    const ctx = await browser.newContext({ ...vp, locale: 'en-US', ignoreHTTPSErrors: true });
    const page = await ctx.newPage(); page.setDefaultTimeout(20000);
    const requests = []; const bodies = [];
    page.on('requestfinished', async (req) => { try { const res = await req.response(); const sizes = await req.sizes(); const mime = res ? (res.headers()['content-type'] || '') : ''; const rec = { url: req.url(), type: req.resourceType(), status: res ? res.status() : null, bytes: sizes.responseBodySize, mime: mime.slice(0, 40) }; requests.push(rec); if (vpName === 'desktop' && res && (req.resourceType() === 'script' || req.resourceType() === 'stylesheet') && sizes.responseBodySize < 4000000) { const t = await res.text().catch(() => ''); if (t) bodies.push({ url: req.url(), kind: req.resourceType() === 'script' ? 'js' : 'css', text: t }); } } catch { } });
    page.on('requestfailed', (req) => { requests.push({ url: req.url(), type: req.resourceType(), status: 'FAILED', failure: (req.failure() || {}).errorText, bytes: 0 }); });
    const consoleErrors = []; page.on('console', m => { if (m.type() === 'error') consoleErrors.push(m.text().slice(0, 200)); }); page.on('pageerror', e => consoleErrors.push('pageerror: ' + String(e.message || e).slice(0, 200)));
    await page.addInitScript(() => { window.__perf = { lcp: 0, lcpEl: null, cls: 0, shifts: [] }; try { new PerformanceObserver((l) => { for (const e of l.getEntries()) { window.__perf.lcp = e.startTime; window.__perf.lcpEl = e.element ? (e.element.tagName + (e.element.className ? '.' + String(e.element.className).slice(0, 40) : '') + (e.element.src ? ' ' + String(e.element.src).slice(0, 80) : '')) : null; } }).observe({ type: 'largest-contentful-paint', buffered: true }); } catch { } try { new PerformanceObserver((l) => { for (const e of l.getEntries()) { if (!e.hadRecentInput) { window.__perf.cls += e.value; window.__perf.shifts.push({ t: Math.round(e.startTime), v: +e.value.toFixed(4) }); } } }).observe({ type: 'layout-shift', buffered: true }); } catch { } });
    const vpResult = { errors: [] }; const t0 = Date.now();
    try { let resp = null, lastErr = null; for (let attempt = 0; attempt < 3; attempt++) { try { resp = await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 }); lastErr = null; break; } catch (e) { lastErr = e; vpResult.errors.push('goto attempt ' + (attempt + 1) + ': ' + e.message.split('\n')[0].slice(0, 120)); await page.waitForTimeout(2500); } } if (lastErr) throw lastErr; vpResult.status = resp ? resp.status() : null; vpResult.finalUrl = page.url(); vpResult.server = resp ? (resp.headers()['server'] || null) : null; vpResult.responseHeaders = resp ? Object.fromEntries(Object.entries(resp.headers()).filter(([k]) => /server|x-powered-by|cache-control|content-encoding|x-vercel|cf-ray|x-nextjs|strict-transport|content-security/.test(k))) : null; await page.waitForLoadState('load', { timeout: 30000 }).catch(() => { }); await page.waitForLoadState('networkidle', { timeout: 12000 }).catch(() => { }); } catch (e) { vpResult.errors.push('goto: ' + e.message.slice(0, 200)); }
    vpResult.loadMs = Date.now() - t0; await page.waitForTimeout(1800);
    vpResult.perfAfterLoad = await page.evaluate(() => { const nav = performance.getEntriesByType('navigation')[0] || {}; const fcp = performance.getEntriesByName('first-contentful-paint')[0]; const p = window.__perf || {}; return { ttfbMs: Math.round(nav.responseStart || 0), domContentLoadedMs: Math.round(nav.domContentLoadedEventEnd || 0), loadMs: Math.round(nav.loadEventEnd || 0), fcpMs: fcp ? Math.round(fcp.startTime) : null, lcpMs: Math.round(p.lcp || 0), lcpElement: p.lcpEl || null, cls: +(p.cls || 0).toFixed(4), resourceCount: performance.getEntriesByType('resource').length, transferKB: Math.round(performance.getEntriesByType('resource').reduce((a, r) => a + (r.transferSize || 0), 0) / 1024) }; }).catch(e => ({ error: e.message }));
    await page.screenshot({ path: path.join(outDir, `${vpName}-hero.png`) }).catch(e => vpResult.errors.push('hero shot: ' + e.message.slice(0, 100)));
    if (!opts.noScroll) { await page.evaluate(async () => { const step = Math.max(300, window.innerHeight * 0.6); let y = 0; const max = () => Math.max(document.body.scrollHeight, document.documentElement.scrollHeight); let guard = 0; while (y < max() && guard < 500) { y += step; window.scrollTo(0, y); await new Promise(r => setTimeout(r, 110)); guard++; } window.scrollTo(0, max()); await new Promise(r => setTimeout(r, 900)); }).catch(() => { }); await page.waitForTimeout(700); await page.evaluate(() => window.scrollTo(0, 0)).catch(() => { }); await page.waitForTimeout(700); }
    vpResult.perfAfterScroll = await page.evaluate(() => { const p = window.__perf || {}; return { cls: +(p.cls || 0).toFixed(4), shifts: (p.shifts || []).slice(0, 12) }; }).catch(() => null);
    // AOS (once:false default) re-hides elements that are below the viewport after scrolling back up; force the revealed state so screenshots show content
    vpResult.aosForced = await page.evaluate(() => { const els = document.querySelectorAll('[data-aos]'); els.forEach(el => el.classList.add('aos-animate')); return els.length; }).catch(() => 0);
    await page.waitForTimeout(400);
    vpResult.data = await page.evaluate(extractInPage, { maxSections: MAX_SECTIONS }).catch(e => ({ error: e.message.slice(0, 300) }));
    await page.screenshot({ path: path.join(outDir, `${vpName}-full.png`), fullPage: true, timeout: 90000 }).catch(e => vpResult.errors.push('full shot: ' + e.message.slice(0, 100)));
    const sections = (vpResult.data && vpResult.data.sections) || [];
    for (const s of sections) { try { await page.evaluate((y) => window.scrollTo(0, Math.max(0, y - 90)), s.top).catch(() => { }); await page.waitForTimeout(650); const clip = { x: 0, y: Math.max(0, s.top), width: vp.viewport.width, height: Math.max(40, Math.min(s.height, 5000)) }; const file = `sections/${vpName}-${String(s.i + 1).padStart(2, '0')}.png`; await page.screenshot({ path: path.join(outDir, file), fullPage: true, clip, timeout: 30000 }); s.screenshot = file; } catch (e) { s.screenshotError = e.message.slice(0, 80); } }
    await page.evaluate(() => window.scrollTo(0, 0)).catch(() => { }); await page.waitForTimeout(300);
    if (vpName === 'desktop' && !opts.noHover) vpResult.hover = await hoverProbe(page).catch(e => ({ error: e.message }));
    if (vpName === 'mobile') { try { const ham = page.locator('[class*="hamburger"], [class*="burger"], [class*="navbar-toggler"], [class*="menu-toggle"], button[aria-label*="menu" i], [class*="menu-btn"], [class*="MobileMenu"] button, header button').first(); if (await ham.count()) { await ham.click({ timeout: 3000, force: true }); await page.waitForTimeout(800); await page.screenshot({ path: path.join(outDir, 'mobile-menu-open.png') }); vpResult.mobileMenuScreenshot = 'mobile-menu-open.png'; } } catch (e) { vpResult.errors.push('mobile menu: ' + e.message.slice(0, 80)); } }
    const byType = {}; let total = 0; const hosts = {}; for (const r of requests) { const t = r.type; byType[t] = byType[t] || { count: 0, kb: 0 }; byType[t].count++; byType[t].kb += Math.round((r.bytes || 0) / 1024); total += r.bytes || 0; try { const h = new URL(r.url).host; hosts[h] = (hosts[h] || 0) + 1; } catch { } }
    const detected = {}; for (const [name, re] of URL_PATTERNS) { const hit = requests.find(r => re.test(r.url)); if (hit) detected[name] = hit.url.slice(0, 140); }
    const sig = {}; if (vpName === 'desktop') { for (const [name, re, kind] of BODY_SIGNATURES) { for (const b of bodies) { if (b.kind !== kind) continue; if (re.global) { const n = (b.text.match(re) || []).length; if (n) { sig[name] = (sig[name] || 0) + n; } continue; } if (re.test(b.text)) { sig[name] = (sig[name] ? sig[name] + ' ; ' : '') + b.url.slice(0, 120); break; } } } }
    vpResult.network = { requests: requests.length, transferKB: Math.round(total / 1024), byType, detectedFromUrls: detected, detectedFromBundleContents: sig, largest: requests.filter(r => r.bytes).sort((a, b) => b.bytes - a.bytes).slice(0, 12).map(r => ({ url: r.url.slice(0, 140), type: r.type, kb: Math.round(r.bytes / 1024) })), failed: requests.filter(r => r.status === 'FAILED' || (typeof r.status === 'number' && r.status >= 400)).slice(0, 20).map(r => ({ url: r.url.slice(0, 140), status: r.status, failure: r.failure })), thirdPartyHosts: Object.entries(hosts).sort((a, b) => b[1] - a[1]).slice(0, 15).map(([h, c]) => `${h} (${c})`) };
    vpResult.consoleErrors = consoleErrors.slice(0, 15);
    await ctx.close(); result.viewports[vpName] = vpResult;
  }
  try { const u = new URL(url); if (u.pathname === '/' || u.pathname === '') { for (const f of ['robots.txt', 'sitemap.xml']) { try { const r = await fetch(u.origin + '/' + f, { redirect: 'follow' }); const t = await r.text(); result[f] = { status: r.status, contentType: r.headers.get('content-type'), preview: t.slice(0, 1200) }; } catch (e) { result[f] = { error: e.message }; } } } } catch { }
  fs.writeFileSync(path.join(outDir, 'data.json'), JSON.stringify(result, null, 2));
  await browser.close();
  const d = result.viewports.desktop || result.viewports.mobile; console.log('OK', slug, 'status', d.status, 'sections', (d.data && d.data.sections || []).length, 'errors', d.errors.length);
})().catch(e => { console.error('FATAL', slug, e.message); process.exit(1); });
